platform :ios, '11.0'
use_frameworks!

target 'FirebaseQueryExecutor_Example' do
  pod 'RxFirestoreExecutor', :path => '../'

  target 'FirebaseQueryExecutor_Tests' do
    inherit! :search_paths


  end
end
