platform :ios, '11.0'


target 'FirebaseQueryExecutor_Example' do
    
    use_frameworks!
    
  pod 'RxFirestoreExecutor', :path => '../'

  target 'FirebaseQueryExecutor_Tests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
#    pod 'RxFirestoreExecutor', :path => '../'

  end
end
